services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - searxng-data:/etc/searxng
    ports:
      - 4000:8080
    environment:
      - SEARXNG_PORT=8080
      - SEARXNG_BIND_ADDRESS=0.0.0.0
    networks:
      - perplexica-network
      - cloudflare-network
    restart: unless-stopped
    labels:
      - "dockflare.enable=true"
      - "dockflare.hostname=searxng.mhs-cloud.com"
      - "dockflare.service=http://searxng:8080"
      - "dockflare.no_tls_verify=true"

  perplexica-api:
    build:
      context: .
      dockerfile: backend.dockerfile
    # image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - perplexica-data:/home/perplexica/data
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
      - cloudflare-network
    restart: unless-stopped
    labels:
      - "dockflare.enable=true"
      - "dockflare.hostname=perplexica-api.mhs-cloud.com"
      - "dockflare.service=http://perplexica-api:3001"
      - "dockflare.no_tls_verify=true"

  perplexica:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://perplexica-api.mhs-cloud.com/api
        - NEXT_PUBLIC_WS_URL=ws://perplexica-api.mhs-cloud.com
    depends_on:
      - perplexica-api
    ports:
      - 3002:3000
    networks:
      - perplexica-network
      - traefik-network
      - cloudflare-network
    restart: unless-stopped
    labels:
      - "dockflare.enable=true"
      - "dockflare.hostname=perplexica.mhs-cloud.com"
      - "dockflare.service=http://perplexica:3000"
      - "dockflare.no_tls_verify=true"

volumes:
  searxng-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/share2/downloads/volumes/perplexica/searxng

  perplexica-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/share2/downloads/volumes/perplexica/data

networks:
  perplexica-network:
    name: perplexica
    external: true

  traefik-network:
    name: traefik
    external: true

  cloudflare-network:
    name: cloudflare-net
    external: true
  

